import Head from 'next/head';
import { useState } from 'react';

export default function Home() {
	const [exercise, setExercise] = useState('Exercise');
	const arrayExercises = [
		'Stretch',
		'Lift',
		'Calisthenics',
		'Walk',
		'Jog',
		'Sprint',
		'Rest',
		'Foam Roll',
		'Walking with Backpack',
		'Swim',
	];

	const generate = () => {
		const randomNumber = Math.floor(Math.random() * arrayExercises.length);
		const randomExercise = arrayExercises[randomNumber];
		setExercise(randomExercise);
	};

	return (
		<div>
			<Head>
				<title>Neomania</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="flex flex-col items-center justify-center h-screen">
				<p>{exercise}</p>
				<button
					onClick={generate}
					className="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded-full"
				>
					Click Me
				</button>
			</div>
		</div>
	);
}
